# Generated by Django 5.2.4 on 2025-07-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(choices=[('Full Service', 'Full Service (Digital Marketing, Web Development, SEO)'), ('Digital Marketing', 'Digital Marketing'), ('Web Development', 'Web Development'), ('SEO', 'SEO')], max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
