# Generated by Django 5.2.4 on 2025-08-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contentmarketinglead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contentmarketinglead',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='contentmarketinglead',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
